### ISSUE TITLE
Training Cost

### ISSUE THREAD

**Issue by Yeez-lee** [chuanyangjin/fast-DiT#10]
Thanks for your efforts. I just want to know how long it will take to train a XL model on ImageNet256 by one A100 GPU in terms of hours.

**Comment by chuanyangjin** [comment]
It'll take several weeks on a single A100 GPU to achieve the best image quality mentioned in the paper. So it's recommended to use multiple A100 GPUs if possible.

**Comment by LiewFeng** [comment]
Hi，@chuanyangjin ,  thank you for your great work. I wonder how long does it take for 8 * A100, on the XL/2, with 256 * 256?
