### ISSUE TITLE
CustomDataset file order

### ISSUE THREAD

**Issue by jiahaoli95** [chuanyangjin/fast-DiT#4]
Thanks for the great work! In L102 of train.py, the feature files and label files are obtained using os.listdir. But os.listdir does not guarantee the returned list the be sorted. Wouldn't this cause mismatch between the feature files and label files? Thank you.

Jiahao

**Comment by chuanyangjin** [comment]
Thank you for highlighting this. I've updated the code with 'sorted' to ensure the lists are in the correct order, addressing your concern.

Chuanyang
