### ISSUE TITLE
Loss scale is different from DiT

### ISSUE THREAD

**Issue by gaopengpjlab** [chuanyangjin/fast-DiT#7]
The Loss for DiT starts from 0.3 while the loss for fast-DiT with cached features starts from 0.03.

**Comment by huzhengdongcs** [comment]
> The Loss for DiT starts from 0.3 while the loss for fast-DiT with cached features starts from 0.03.

Hi, I meet the same problem. Has this issue been resolved?

**Comment by chuanyangjin** [comment]
DiT and fast-DiT are expected to have the same loss scale and follow similar loss curves, as verified by different people. So I'm unsure why there's such a discrepancy in your case.

**Comment by 649459021** [comment]
> The Loss for DiT starts from 0.3 while the loss for fast-DiT with cached features starts from 0.03.

Hi, have you solved this problem?
